default: &default
  image: 99taxis/activator
  ports:
    - 9000:9000
  volumes:
    - ./:/app
    - ~/.ivy2:/root/.ivy2
    - ~/.m2:/root/.m2

sbt:
  <<: *default
  command: sbt

c:
  <<: *default
  command: /bin/bash
